version: '2'
services:
        ranzhi:
                image: 'snowind/ranzhi:latest'
                container_name: ranzhi
                restart: always
                ports:
                        - "80:80"
                        - "3306:3306"
                volumes:
                        - /home/ranzhi/service:/var/ranzhi
                        - /home/ranzhi/mysql:/var/lib/mysql
                        - /home/ranzhi/ssl:/etc/ssl:ro
                environment:
                        - IS_HTTPS=YES
                        - MYSQL_ADMIN_USER=admin
                        - MYSQL_ADMIN_PASS=admin888
                        - SSL_CERT_FILE=/etc/apache2/ssl/ranzhi.crt
                        - SSL_CERT_KEY_FILE=/etc/apache2/ssl/ranzhi.key

